-- PROJECT EULER : problem 29
-- How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

import Data.List ( nub, sort )

powers = [ a ^ b | a <- [ 2 .. 100 ], b <- [ 2 .. 100 ] ]

res = length . sort . nub $ powers

main :: IO ()
main = print res
